# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

from cryptography.hazmat.primitives.asymmetric import mlkem
from cryptography.utils import Buffer

class MlKem768PrivateKey: ...
class MlKem768PublicKey: ...

def generate_key() -> mlkem.MlKem768PrivateKey: ...
def from_seed_bytes(data: Buffer) -> mlkem.MlKem768PrivateKey: ...
def from_public_bytes(data: Buffer) -> mlkem.MlKem768PublicKey: ...
